name: BusBuzz CI/CD to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0


      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -var="github_repo_url=https://github.com/sierrahotel777/BusBuzz.git"
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="github_repo_url=${{ github.repository_url }}"
        working-directory: ./terraform
